name: Gh-Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1

      - name: Set up .env file
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          echo GEMINI_API_KEY=$GEMINI_API_KEY > .env

      - name: Display GEMINI_API_KEY from secrets
        run: echo ${{ secrets.GEMINI_API_KEY }}

      - name: Display GEMINI_API_KEY from .env file
        run: cat .env

      - name: Deploy to GitHub Pages
        uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /Portfolio_Website/
