name: Gh-Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Only works with v2 and must have write permissions from github actions.
      - uses: subosito/flutter-action@v1
      - uses: bluefireteam/flutter-gh-pages@v7